/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.somi92.seecsk.gui;

import com.github.somi92.seecsk.domain.Clan;
import com.github.somi92.seecsk.gui.panels.CategoriesGroupsPanel;
import com.github.somi92.seecsk.gui.panels.MembersPanel;
import com.github.somi92.seecsk.model.controllers.KontrolerPL;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author milos
 */
public class FMainForm extends javax.swing.JFrame {

    /**
     * Creates new form FMainForm
     */
    public FMainForm() {
        initComponents();
        initPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlMainPanel = new javax.swing.JPanel();
        jmnuMenuBar = new javax.swing.JMenuBar();
        jmnuMain = new javax.swing.JMenu();
        jmnuiMembers = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnuApp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEECSK - Sistem za elektronsku evidenciju članova sportskog kluba");

        jpnlMainPanel.setLayout(new java.awt.CardLayout());

        jmnuMain.setText("Glavni meni");

        jmnuiMembers.setText("Članovi kluba");
        jmnuiMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiMembersActionPerformed(evt);
            }
        });
        jmnuMain.add(jmnuiMembers);

        jMenuItem1.setText("Panel1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnuMain.add(jMenuItem1);

        jMenuItem2.setText("Panel2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnuMain.add(jMenuItem2);

        jmnuMenuBar.add(jmnuMain);

        jmnuApp.setText("Aplikacija");
        jmnuMenuBar.add(jmnuApp);

        setJMenuBar(jmnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jpnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnuiMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiMembersActionPerformed
        FMembers fMembers = new FMembers();
        fMembers.setVisible(true);
    }//GEN-LAST:event_jmnuiMembersActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel1");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cl = (CardLayout) jpnlMainPanel.getLayout();
        cl.show(jpnlMainPanel, "panel2");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmnuApp;
    private javax.swing.JMenu jmnuMain;
    private javax.swing.JMenuBar jmnuMenuBar;
    private javax.swing.JMenuItem jmnuiMembers;
    private javax.swing.JPanel jpnlMainPanel;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {
        MembersPanel panel1 = new MembersPanel();
        CategoriesGroupsPanel panel2 = new CategoriesGroupsPanel();
        jpnlMainPanel.add("panel1", panel1);
        jpnlMainPanel.add("panel2", panel2);
    }
}
